### ISSUE TITLE
Can you make this telegram theme for Android?

### ISSUE THREAD

**Issue by lyaurora** [makipom/MomoTalk-Telegram#1]
I really want the Android version of the theme, but I'm not sure how it will look on Android.

**Comment by makipom** [comment]
Due to how this theme was made in the first place, porting it into mobile platforms would almost mean building it again from scratch. 

I tried porting it using third-party conversion software during earlier stages of development, but it brought bad results. And by this point in time, this theme is even more complex, with many settings changed (or not even present in the first place) on mobile platforms, to the point that re-creating it for mobile would prove to be a deed requesting much time of me - time that I can not and am not willing to spare for the task of re-doing this theme from zero. 

So, sadly, even though Momotalk in-game is definitely a mobile (tablet) application, this exact theme wouldn't be released on mobile in the foreseeable future.

_tl;dr_ - **Sadly, yet certainly, no.**

**Comment by lyaurora** [comment]
thx😇
